# docker build -f Dockerfile.glot -t glot/huatuo .
FROM registry.cn-chengdu.aliyuncs.com/mgame/ubuntu-mono

RUN groupadd glot
RUN useradd -d /home/glot -g glot -s /bin/bash glot

ADD Glot-Linux /Builds
RUN chmod +x /Builds/huatuo

ADD images/code-runner_linux-x64.tar.gz /

CMD [ "/code-runner", "--path", "/home/glot" ]
